spring:
  application:
    name: test-config
  profiles:
    active: dev
#配置中心
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KobeG/KobeG.git
          search-paths: user　　//配置文件目录，多个用逗号隔开
          username: KobeG
          password: qg19121994
          default-label: master
          basedir: ./configRepo/　　//本地缓存地址
          force-pull: true　　//强制拉取配置，解决手动修改本地缓存配置后，无法拉取最新配置的问题

# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
